### ISSUE TITLE
能否给我一下适配vue2.7相关低代码权限，谢谢

### ISSUE THREAD

**Issue by ZMDreamer** [cdLab996/lowcode-engine-demo-vue#5]
事后加微信必有重谢，微信号：zm1101370783

**Comment by WuChenDi** [comment]
可能会有些不便，因为涉及到的包较多。

实际上，我是在 [KNXCloud/lowcode-engine-vue](https://github.com/KNXCloud/lowcode-engine-vue) 的基础上进行适配，以兼容 2.7 版本。

在修改适配的基础上，如果您有任何问题，欢迎随时咨询。

**Comment by ZMDreamer** [comment]
能否加个微信，有问题咨询一下呢
