### ISSUE TITLE
请假一个问题

### ISSUE THREAD

**Issue by nyanboard** [cdLab996/lowcode-engine-demo-vue#6]
@cdlab996/element-lowcode-materials2.7

这个包你是怎么打包的，目前我们也在研究vue2.0的组件打包

**Comment by WuChenDi** [comment]
This is a package I have meticulously crafted for Vue2.x [@cdlab996/vue-cli-plugin-lowcode2.7](https://www.npmjs.com/package/@cdlab996/vue-cli-plugin-lowcode2.7)

This is a fork [vue-cli-plugin-lowcode](https://github.com/KNXCloud/lowcode-engine-tools/tree/main/packages/vue-cli-plugin-lowcode)
